#curl some.domain/hostname
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: default-config
  namespace: test
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /hostname {
            root   /etc;
        }

        location /remote_addr {
            default_type text/plain;
            return 200 "$remote_addr\n";
        }

        location /server_addr {
            default_type text/plain;
            return 200 "$server_addr\n";
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:8080
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    } 
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: test-net-service
  name: test-net-service
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-net-service
  template:
    metadata:
      labels:
        app: test-net-service
    spec:
      containers:
      - image: burlyluo/nettoolbox
        name: nettoolbox
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: default-config
            readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.conf
                path: default.conf
            name: default-config
          name: default-config
---

apiVersion: v1
kind: Service
metadata:
  name: test-net-service-svc
  namespace: test
  labels:
    app: test-net-service
spec:
  clusterIP: 10.96.250.110
  clusterIPs:
  - 10.96.250.110
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test-net-service
  type: ClusterIP



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test-net-ds
  name: test-net-ds
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-net-ds
  template:
    metadata:
      labels:
        app: test-net-ds
    spec:
      containers:
      - image: burlyluo/nettoolbox
        name: nettoolbox
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: default-config
            readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.conf
                path: default.conf
            name: default-config
          name: default-config
